version: '3.8'

services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@localhost.local
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:80"
#    volumes:
#      - pgadmin-data:/home
#   Сервис будет запущен, только после старта db
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:${PGDATA}

#  adminer:
#    container_name: adminer_container
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes:
#      - adminer-data:/home


volumes:
  db-data:
#  pgadmin-data:
#  adminer-data:
