version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    volumes:
      - db-data:${PGDATA}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - adminer-data:/home


volumes:
  db-data:
  adminer-data:
